# Generated by Django 4.2.6 on 2023-10-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('creator', models.CharField(default='', max_length=42)),
                ('collection', models.CharField(default='', max_length=42)),
                ('token_id', models.IntegerField()),
                ('payment_token', models.CharField(default='', max_length=42)),
                ('bidder_sig', models.CharField(default=None, max_length=132)),
                ('amount', models.BigIntegerField(default=None)),
            ],
        ),
    ]
